### ISSUE TITLE
Adding Xen device tree should really be an overlay

### ISSUE THREAD

**Issue by cminyard** [dornerworks/xen-rpi4-builder#10]
Having a whole new device tree for Xen is really not the right way to handle this for a Pi.  I've attached a small patch that has an overload to add Xen, and I have tested it.  I have not fully integrated it into your build scripts, but I can if you like and then provide a merge request.
[0001-Add-Xen-overlay-for-the-Pi-4.patch.txt](https://github.com/dornerworks/xen-rpi4-builder/files/4493714/0001-Add-Xen-overlay-for-the-Pi-4.patch.txt)

**Comment by stewdk** [comment]
I would be happy to accept a merge request for this.

**Comment by cminyard** [comment]
Ok, this is done.
