### ISSUE TITLE
error "No rule to make target" when running the script

### ISSUE THREAD

**Issue by paadam94** [dornerworks/xen-rpi4-builder#13]
I got this message:
```
++ nproc
+ make O=.build-arm64 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j 2 overlays/pi4-64-xen.dtbo
make[1]: Entering directory '/home/adam/xen-rpi4-builder/linux/.build-arm64'
make[2]: *** No rule to make target 'arch/arm64/boot/dts/overlays/pi4-64-xen.dtbo'.  Stop.
make[1]: *** [arch/arm64/Makefile:135: overlays/pi4-64-xen.dtbo] Error 2
make[1]: Leaving directory '/home/adam/xen-rpi4-builder/linux/.build-arm64'
make: *** [Makefile:146: sub-make] Error 2
```
I uploaded a more compete output, and the contents of xen-rpi4-builder/linux/.build-arm64/.config.
[output](https://sharetxt.xyz/id?3337)
[.config](https://sharetxt.xyz/id?6817)

also I posted question about installing xen on rpi in general on the raspberry stack exchange:
[related question on raspberry stackexchange](https://raspberrypi.stackexchange.com/questions/120686/how-to-get-xen-run-on-a-headless-raspi4)

**Comment by stewdk** [comment]
Did patches/linux/0001-Add-Xen-overlay-for-the-Pi-4.patch get correctly applied in your linux repo?

**Comment by paadam94** [comment]
I'm not sure how to check that, but I checked /linux/arch/arm/boot/dts/overlays and I didn't find the pi4-32-xen-overlay.dts, and I guess that's the file supposed to be patched. Problem seems to be not that It haven't been patched but it's not even exsisting :S

**Comment by stewdk** [comment]
The patch creates the files pi4-32-xen-overlay.dts and pi4-64-xen-overlay.dts. Correct, they shouldn't exist before the patch is applied. See rpixen.sh line 47 to see how the patches get applied.

**Comment by paadam94** [comment]
Ran the command manually, turned out that I had to add my email and name to the "gitconfig" -.- . After I configured it, It ran perfectly, the img had been created. Thanks!
