### ISSUE TITLE
username : dornerworks and password : dornerworks is incorrect！

### ISSUE THREAD

**Issue by AFunnyMan** [dornerworks/xen-rpi4-builder#14]
username : dornerworks
password : dornerworks

_Originally posted by @marvinyane in https://github.com/dornerworks/xen-rpi4-builder/issues/6#issuecomment-571062108_

Can you give me password?Thank you!

**Comment by stewdk** [comment]
username : dornerworks and password : dornerworks is correct. I suspect the build script may not have completed. Please re-build and ensure the script runs to completion without errors.

**Comment by AFunnyMan** [comment]
Thank you!
