### ISSUE TITLE
WiFi not working

### ISSUE THREAD

**Issue by tklengyel** [dornerworks/xen-rpi4-builder#5]
After the system boots no wifi interface is present. The following line shows up in the dmesg however:

`[  164.429172] brcmfmac: brcmf_sdio_htclk: HT Avail timeout (1000000): clkctl 0x50`

I've tried manually load brcmfmac43455-sdio blobs from https://github.com/RPi-Distro/firmware-nonfree/tree/master/brcm manually but it results in the system freezing up. I don't have serial access on the system (only ssh) so I couldn't investigate any further.

**Comment by salerio-gs** [comment]
Has there been any progress on getting this working?

**Comment by stewdk** [comment]
Wifi is working with commit f80c5cafe34db13a05a50976959aef98d361a6d0.
