### ISSUE TITLE
..How to log in?

### ISSUE THREAD

**Issue by RonnieTiger** [dornerworks/xen-rpi4-builder#6]
The lack of HDMI support makes using this image next to impossible out of the box. 

A default login isn't documented anywhere, and poking around the generated image, the only user besides root seems to be 

dornerworks:x:1000:1000::/home/dornerworks:/bin/bash

After trying a few times the password appears to be dornerworks, but this isn't documented anywhere. 

Please add documentation for the default login.

**Comment by tklengyel** [comment]
+1, I also had to look for this after the first install

**Comment by marvinyane** [comment]
username : dornerworks
password : dornerworks

**Comment by ep1cman** [comment]
I can see those credentials in the script, but when I try to use them to log in they dont work :(

**Comment by stewdk** [comment]
The credentials are now documented in the README. Regarding incorrect credentials, please re-build and ensure the script runs to completion without errors. HDMI is being tracked in a separate issue.
